---
abstract: 'run SQL from a file'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  Data::Dumper: '0'
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBIx-RunSQL
no_index:
  directory:
    - t
    - inc
requires:
  DBI: '0'
  Getopt::Long: '2.36'
  Module::Load: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=DBIx-RunSQL
  license: http://dev.perl.org/licenses/
  repository: git://github.com/Corion/dbix--runsql.git
version: '0.21'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
